export function formatCountry(countryCode?: string | null): string {
  if (!countryCode) return "未知国家 (Unknown)";
  const code = countryCode.toUpperCase().trim();
  const map: Record<string, string> = {
    US: "🇺🇸 美国 (United States)",
    MX: "🇲🇽 墨西哥 (Mexico)",
    CA: "🇨🇦 加拿大 (Canada)",
    AU: "🇦🇺 澳大利亚 (Australia)",
    GB: "🇬🇧 英国 (United Kingdom)",
    DE: "🇩🇪 德国 (Germany)",
    FR: "🇫🇷 法国 (France)",
    ES: "🇪🇸 西班牙 (Spain)",
    IT: "🇮🇹 意大利 (Italy)",
    NL: "🇳🇱 荷兰 (Netherlands)",
    CO: "🇨🇴 哥伦比亚 (Colombia)",
    CL: "🇨🇱 智利 (Chile)",
    BR: "🇧🇷 巴西 (Brazil)",
    AR: "🇦🇷 阿根廷 (Argentina)",
    PE: "🇵🇪 秘鲁 (Peru)",
    SA: "🇸🇦 沙特阿拉伯 (Saudi Arabia)",
    AE: "🇦🇪 阿联酋 (UAE)",
    JP: "🇯🇵 日本 (Japan)",
    KR: "🇰🇷 韩国 (South Korea)",
    SG: "🇸🇬 新加坡 (Singapore)",
    NZ: "🇳🇿 新西兰 (New Zealand)",
    ZA: "🇿🇦 南非 (South Africa)",
    RO: "🇷🇴 罗马尼亚 (Romania)",
    PL: "🇵🇱 波兰 (Poland)",
    SE: "🇸🇪 瑞典 (Sweden)",
    NO: "🇳🇴 挪威 (Norway)",
    DK: "🇩🇰 丹麦 (Denmark)",
    FI: "🇫🇮 芬兰 (Finland)",
    CH: "🇨🇭 瑞士 (Switzerland)",
    AT: "🇦🇹 奥地利 (Austria)",
    BE: "🇧🇪 比利时 (Belgium)",
    IE: "🇮🇪 爱尔兰 (Ireland)",
    PT: "🇵🇹 葡萄牙 (Portugal)",
    GR: "🇬🇷 希腊 (Greece)",
    TR: "🇹🇷 土耳其 (Turkey)",
    RU: "🇷🇺 俄罗斯 (Russia)",
    IN: "🇮🇳 印度 (India)",
    MY: "🇲🇾 马来西亚 (Malaysia)",
    PH: "🇵🇭 菲律宾 (Philippines)",
    TH: "🇹🇭 泰国 (Thailand)",
    VN: "🇻🇳 越南 (Vietnam)",
    ID: "🇮🇩 印度尼西亚 (Indonesia)",
    CN: "🇨🇳 中国 (China/Internal)",
    HK: "🇭🇰 中国香港 (Hong Kong)",
    TW: "🇹🇼 中国台湾 (Taiwan)",
  };

  return map[code] || `🌐 境外买手 (${code})`;
}
